-- AlterEnum: notification types for the contract workflow
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CONTRACT_MILESTONES_SET';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CONTRACT_ACTIVATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CONTRACT_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CONTRACT_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MILESTONE_REVISION_REQUESTED';
